/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_appsync_graphqlEndpoint": "https://23ofku7otjec5cg3c3xszpro7i.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-nxjuka4l2zauvbcbj2bltqhq2a",
    "aws_cognito_identity_pool_id": "us-east-1:511e777f-4bc0-48e9-96c3-19db150e5367",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_xp47bZGLy",
    "aws_user_pools_web_client_id": "218fl8votgb2p5rn6fovjlhm2m",
    "oauth": {},
    "aws_cognito_username_attributes": [],
    "aws_cognito_social_providers": [],
    "aws_cognito_signup_attributes": [
        "EMAIL"
    ],
    "aws_cognito_mfa_configuration": "OFF",
    "aws_cognito_mfa_types": [
        "SMS"
    ],
    "aws_cognito_password_protection_settings": {
        "passwordPolicyMinLength": 8,
        "passwordPolicyCharacters": []
    },
    "aws_cognito_verification_mechanisms": [
        "EMAIL"
    ],
    "geo": {
        "amazon_location_service": {
            "region": "us-east-1",
            "geofenceCollections": {
                "items": [
                    "geofenceCollection2ac66f7b-dev"
                ],
                "default": "geofenceCollection2ac66f7b-dev"
            },
            "maps": {
                "items": {
                    "mapea866995-dev": {
                        "style": "VectorEsriStreets"
                    }
                },
                "default": "mapea866995-dev"
            }
        }
    }
};


export default awsmobile;
